// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module Datapath_Vers4 (

  input wire [31:0] i_Instruction,
  input wire [31:0] i_Memory_data,
  input wire i_PC_write_enable,
  output wire [31:0] o_Memory,
  input wire [31:0] i_ZERO,
  input wire i_write_enable,
  input wire [2:0] i_Write_Back_Sel,
  input wire [3:0] i_ALU_Op,
  input wire i_A_Sel,
  input wire i_B_Sel,
  input wire i_Start,
  output wire o_Branch_Taken,
  input wire i_MUX_Sel,
  input wire i_Rst,
  input wire i_Clk,
  input wire [2:0] i_Branch_Sel

);

//Internal Wires
 wire [31:0] w_1;
 wire [31:0] w_2;
 wire [31:0] w_3;
 wire [31:0] w_4;
 wire [31:0] w_7;
 wire [31:0] w_8;
 wire [31:0] w_9;
 wire [31:0] w_13;
 wire [31:0] w_17;
 wire [31:0] w_18;
 wire [31:0] w_20;
 wire [31:0] w_23;
 wire [31:0] w_24;
 wire [31:0] w_26;
 wire [31:0] w_28;

//Instances of Modules
RISCV_CRC blk3334_70 (
         .i_Start (i_Start),
         .i_Rst (i_Rst),
         .i_Clk (i_Clk),
         .i_Register_Rs_1 (w_1),
         .i_Register_Rs_2 (w_2),
         .i_Instruction (w_3),
         .o_Result (w_4)
     );

RISCV_ALU_4bit blk3287_74 (
         .i_ALU_Op (i_ALU_Op [3:0]),
         .i_A_Sel (i_A_Sel),
         .i_B_Sel (i_B_Sel),
         .i_Register_Rs_1 (w_1),
         .i_Register_Rs_2 (w_2),
         .i_PC_Output (w_7),
         .i_Immediate (w_8),
         .o_Q (w_9)
     );

RISCV_IMM_GENERATOR_A blk3362_75 (
         .o_Immediate (w_8),
         .i_Instruction (w_3)
     );

RISCV_BRANCH_COMPARATOR_A blk3363_76 (
         .o_Branch_Taken (o_Branch_Taken),
         .i_Branch_Sel (i_Branch_Sel [2:0]),
         .i_Reg_A (w_1),
         .i_Reg_B (w_2)
     );

A_register blk2705_77 (
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_out (w_1),
         .data_in (w_13)
     );

instruction_register blk2703_78 (
         .data_in (i_Instruction [31:0]),
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_out (w_3)
     );

memorydata_register blk2704_79 (
         .data_in (i_Memory_data [31:0]),
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_out (w_17)
     );

B_register blk2706_80 (
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_out (w_2),
         .data_in (w_18)
     );

ALU_Out_Register blk2708_81 (
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_in (w_9),
         .data_out (w_20)
     );

PROGRAM_COUNTER_A blk3367_83 (
         .i_PC_write_enable (i_PC_write_enable),
         .i_Rst (i_Rst),
         .i_Clk (i_Clk),
         .i_Data (w_23),
         .o_PC_Output (w_24),
         .o_PC_Plus_4 (w_26)
     );

MUX2_32 blk1779_84 (
         .Z (o_Memory [31:0]),
         .S (i_MUX_Sel),
         .B (w_20),
         .A (w_24)
     );

old_PC_Register blk3485_88 (
         .write_enable (i_write_enable),
         .reset (i_Rst),
         .clk (i_Clk),
         .data_out (w_7),
         .data_in (w_24)
     );

MUX2_32 blk1779_89 (
         .S (i_MUX_Sel),
         .B (w_20),
         .Z (w_23),
         .A (w_26)
     );

RISCV_Register3bit_A blkProj14723_102 (
         .i_ZERO (i_ZERO [31:0]),
         .i_Write_Enable (i_write_enable),
         .i_Write_Back_Sel (i_Write_Back_Sel [2:0]),
         .i_Rst (i_Rst),
         .i_Clk (i_Clk),
         .i_CRC_Result (w_4),
         .o_Data_Rs_1 (w_13),
         .i_Instruction (w_3),
         .i_Memory_Data (w_17),
         .o_Data_Rs_2 (w_18),
         .i_ALU_Output (w_20),
         .i_PC_Plus_4 (w_26),
         .i_Multiplier_Result (w_28)
     );

RISCV_Multiplier blk3040_104 (
         .i_Start (i_Start),
         .i_Rst (i_Rst),
         .i_Clk (i_Clk),
         .i_Multiplier (w_1),
         .i_Instruction (w_3),
         .i_Multiplicand (w_2),
         .o_Result (w_28)
     );


endmodule
